# Generated by Django 4.1.1 on 2022-09-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('serieproducto', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[['Dell', 'Dell'], ['HP', 'HP'], ['Lenovo', 'Lenovo'], ['Epson', 'Epson'], ['Samsung', 'Samsung'], ['Alcatel', 'Alcatel'], ['Generico', 'Generico']], max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('procesador', models.CharField(max_length=50)),
                ('so', models.CharField(choices=[['Windows 7 x32', 'Windows 7 x32'], ['Windows 7 x64', 'Windows 7 x64'], ['Windows 10 x32', 'Windows 10 x32'], ['Windows 10 x64', 'Windows 10 x64'], ['Android', 'Android']], max_length=100)),
                ('hdd', models.CharField(choices=[['100GB', '100GB'], ['200GB', '200GB'], ['256GB', '256GB'], ['500GB', '500GB'], ['1TB', '1TB']], max_length=100)),
                ('ram', models.CharField(choices=[['2GB', '2GB'], ['4GB', '4GB'], ['8GB', '8GB'], ['16GB', '16GB'], ['32GB', '32GB']], max_length=100)),
                ('ip', models.CharField(max_length=50)),
                ('asignacion', models.CharField(max_length=50)),
                ('departamento', models.CharField(choices=[['Informatica', 'Informatica'], ['Corporativo', 'Corporativo'], ['Ventas', 'Ventas'], ['BTA', 'BTA'], ['BTG', 'BTG'], ['BTO', 'BTO'], ['Administracion', 'Administracion'], ['Operaciones', 'Operaciones'], ['Gerencia General', 'Gerencia General'], ['KAM', 'KAM'], ['Despacho', 'Despacho']], max_length=50)),
                ('estado', models.CharField(choices=[['nuevo', 'nuevo'], ['usado', 'usado'], ['Activo', 'Activo'], ['Desuso', 'Desuso']], max_length=100)),
                ('observaciones', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Impresoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('serieproducto', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[['Dell', 'Dell'], ['HP', 'HP'], ['Lenovo', 'Lenovo'], ['Epson', 'Epson'], ['Samsung', 'Samsung'], ['Alcatel', 'Alcatel'], ['Generico', 'Generico']], max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('asignacion', models.CharField(max_length=50)),
                ('departamento', models.CharField(choices=[['Informatica', 'Informatica'], ['Corporativo', 'Corporativo'], ['Ventas', 'Ventas'], ['BTA', 'BTA'], ['BTG', 'BTG'], ['BTO', 'BTO'], ['Administracion', 'Administracion'], ['Operaciones', 'Operaciones'], ['Gerencia General', 'Gerencia General'], ['KAM', 'KAM'], ['Despacho', 'Despacho']], max_length=50)),
                ('estado', models.CharField(choices=[['nuevo', 'nuevo'], ['usado', 'usado'], ['Activo', 'Activo'], ['Desuso', 'Desuso']], max_length=100)),
                ('observaciones', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Monitores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('serieproducto', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[['Dell', 'Dell'], ['HP', 'HP'], ['Lenovo', 'Lenovo'], ['Epson', 'Epson'], ['Samsung', 'Samsung'], ['Alcatel', 'Alcatel'], ['Generico', 'Generico']], max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('asignacion', models.CharField(max_length=50)),
                ('departamento', models.CharField(choices=[['Informatica', 'Informatica'], ['Corporativo', 'Corporativo'], ['Ventas', 'Ventas'], ['BTA', 'BTA'], ['BTG', 'BTG'], ['BTO', 'BTO'], ['Administracion', 'Administracion'], ['Operaciones', 'Operaciones'], ['Gerencia General', 'Gerencia General'], ['KAM', 'KAM'], ['Despacho', 'Despacho']], max_length=50)),
                ('estado', models.CharField(choices=[['nuevo', 'nuevo'], ['usado', 'usado'], ['Activo', 'Activo'], ['Desuso', 'Desuso']], max_length=100)),
                ('observaciones', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Perifericos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_periferico', models.CharField(choices=[['Teclado', 'Teclado'], ['Mouse', 'Mouse'], ['Audifonos', 'Audifonos'], ['Adaptador inalambrico', 'Adaptador inalambrico'], ['Webcam', 'Webcam'], ['Otros', 'Otros']], max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('serieproducto', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[['Dell', 'Dell'], ['HP', 'HP'], ['Lenovo', 'Lenovo'], ['Epson', 'Epson'], ['Samsung', 'Samsung'], ['Alcatel', 'Alcatel'], ['Generico', 'Generico']], max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('asignacion', models.CharField(max_length=50)),
                ('departamento', models.CharField(choices=[['Informatica', 'Informatica'], ['Corporativo', 'Corporativo'], ['Ventas', 'Ventas'], ['BTA', 'BTA'], ['BTG', 'BTG'], ['BTO', 'BTO'], ['Administracion', 'Administracion'], ['Operaciones', 'Operaciones'], ['Gerencia General', 'Gerencia General'], ['KAM', 'KAM'], ['Despacho', 'Despacho']], max_length=50)),
                ('estado', models.CharField(choices=[['nuevo', 'nuevo'], ['usado', 'usado'], ['Activo', 'Activo'], ['Desuso', 'Desuso']], max_length=100)),
                ('observaciones', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Telefonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_telefonia', models.IntegerField(choices=[['Fijo', 'Fijo'], ['Movil', 'Movil']])),
                ('codigo', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[['Dell', 'Dell'], ['HP', 'HP'], ['Lenovo', 'Lenovo'], ['Epson', 'Epson'], ['Samsung', 'Samsung'], ['Alcatel', 'Alcatel'], ['Generico', 'Generico']], max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('so', models.CharField(choices=[['Windows 7 x32', 'Windows 7 x32'], ['Windows 7 x64', 'Windows 7 x64'], ['Windows 10 x32', 'Windows 10 x32'], ['Windows 10 x64', 'Windows 10 x64'], ['Android', 'Android']], max_length=100)),
                ('asignacion', models.CharField(max_length=50)),
                ('departamento', models.CharField(choices=[['Informatica', 'Informatica'], ['Corporativo', 'Corporativo'], ['Ventas', 'Ventas'], ['BTA', 'BTA'], ['BTG', 'BTG'], ['BTO', 'BTO'], ['Administracion', 'Administracion'], ['Operaciones', 'Operaciones'], ['Gerencia General', 'Gerencia General'], ['KAM', 'KAM'], ['Despacho', 'Despacho']], max_length=50)),
                ('estado', models.CharField(choices=[['nuevo', 'nuevo'], ['usado', 'usado'], ['Activo', 'Activo'], ['Desuso', 'Desuso']], max_length=100)),
                ('observaciones', models.CharField(max_length=150)),
            ],
        ),
    ]
