# Generated by Django 4.1.1 on 2022-10-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTIPRO', '0002_alter_equipos_asignacion_alter_impresoras_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonia',
            name='tipo_telefonia',
            field=models.IntegerField(choices=[['Telefonia fija', 'Telefonia fija'], ['Telefonia movil', 'Telefonia movil']]),
        ),
    ]
