# Generated by Django 4.1.1 on 2022-10-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTIPRO', '0003_alter_telefonia_tipo_telefonia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonia',
            name='tipo_telefonia',
            field=models.CharField(choices=[['Telefonia fija', 'Telefonia fija'], ['Telefonia movil', 'Telefonia movil']], max_length=50),
        ),
    ]
