# Generated by Django 4.1.1 on 2022-10-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTIPRO', '0004_alter_telefonia_tipo_telefonia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipos',
            old_name='ip',
            new_name='direccion_ip',
        ),
        migrations.AlterField(
            model_name='telefonia',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
