# Generated by Django 4.1.1 on 2022-10-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTIPRO', '0005_rename_ip_equipos_direccion_ip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipos',
            old_name='hdd',
            new_name='disco_duro',
        ),
        migrations.RenameField(
            model_name='equipos',
            old_name='ram',
            new_name='memoria_ram',
        ),
        migrations.RenameField(
            model_name='equipos',
            old_name='so',
            new_name='sistema_operativo',
        ),
        migrations.RenameField(
            model_name='telefonia',
            old_name='so',
            new_name='sistema_operativo',
        ),
        migrations.AddField(
            model_name='equipos',
            name='hostname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='impresoras',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='monitores',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='perifericos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
