# Generated by Django 4.1.1 on 2022-10-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTIPRO', '0006_rename_hdd_equipos_disco_duro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
