# Generated by Django 4.1.1 on 2022-10-23 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTIPRO', '0007_alter_equipos_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(choices=[['Boggie, Maria Fernanda', 'Boggie, Maria Fernanda'], ['Bravo, Marta Jimena', 'Bravo, Marta Jimena'], ['Bustamante, Luis Armando', 'Bustamante, Luis Armando'], ['Cardenas, Daisy Dayana', 'Cardenas, Daisy Dayana'], ['Caviedes, Manuel Enrique', 'Caviedes, Manuel Enrique'], ['Céspedes, Casandra Catalina', 'Céspedes, Casandra Catalina'], ['Gonzalez, Erica Del Carmen', 'Gonzalez, Erica Del Carmen'], ['Gonzalez, Margarita Del Carmen', 'Gonzalez, Margarita Del Carmen'], ['Grandon, Pamela Loreto', 'Grandon, Pamela Loreto'], ['Hermosilla, Valois Eleazar', 'Hermosilla, Valois Eleazar'], ['Hernandez, America', 'Hernandez, America'], ['Jantzent, Fernando', 'Jantzent, Fernando'], ['Jimenez, Gianina Andrea', 'Jimenez, Gianina Andrea'], ['Kromschroder, Juan Oscar', 'Kromschroder, Juan Oscar'], ['Kromschroder, Juan', 'Kromschroder, Juan'], ['Luna, Natalia Andrea', 'Luna, Natalia Andrea'], ['Meneses, Yesenia Jackeline', 'Meneses, Yesenia Jackeline'], ['Merchan, Gisselle Karolina', 'Merchan, Gisselle Karolina'], ['Navarro, Julio Esteban', 'Navarro, Julio Esteban'], ['Olea, Mireya Pamela', 'Olea, Mireya Pamela'], ['Ramirez, Carlos Rafael', 'Ramirez, Carlos Rafael'], ['Sanchez, Yineth Esperanza', 'Sanchez, Yineth Esperanza'], ['Toro, Maritza Soledad', 'Toro, Maritza Soledad'], ['Valenzuela, Karina Andrea', 'Valenzuela, Karina Andrea'], ['Vargas, Karina Andrea', 'Vargas, Karina Andrea'], ['Venegas, Carlos Sebastian', 'Venegas, Carlos Sebastian'], ['Vera, Nelly', 'Vargas, Vera, Nelly'], ['Zamora, Francisco Javier', 'Zamora, Francisco Javier']], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipos',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='impresoras',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='monitores',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='perifericos',
            name='asignacion',
        ),
        migrations.RemoveField(
            model_name='telefonia',
            name='asignacion',
        ),
        migrations.AddField(
            model_name='equipos',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.persona'),
        ),
        migrations.AddField(
            model_name='impresoras',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.persona'),
        ),
        migrations.AddField(
            model_name='monitores',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.persona'),
        ),
        migrations.AddField(
            model_name='perifericos',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.persona'),
        ),
        migrations.AddField(
            model_name='telefonia',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.persona'),
        ),
    ]
