# Generated by Django 4.1.1 on 2022-10-23 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTIPRO', '0008_persona_remove_equipos_asignacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='impresoras',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='monitores',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='perifericos',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='telefonia',
            name='persona',
        ),
        migrations.AddField(
            model_name='persona',
            name='equipos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.equipos'),
        ),
        migrations.AddField(
            model_name='persona',
            name='impresoras',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.impresoras'),
        ),
        migrations.AddField(
            model_name='persona',
            name='monitores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.monitores'),
        ),
        migrations.AddField(
            model_name='persona',
            name='perifericos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.perifericos'),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefonia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.telefonia'),
        ),
    ]
