# Generated by Django 4.1.1 on 2022-10-23 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTIPRO', '0009_remove_equipos_persona_remove_impresoras_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='impresoras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.impresoras'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='monitores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.monitores'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='perifericos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.perifericos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefonia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.telefonia'),
        ),
    ]
