# Generated by Django 4.1.1 on 2022-10-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTIPRO', '0011_departamento_persona_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='tipo',
            field=models.CharField(choices=[['DESKTOP', 'DESKTOP'], ['LAPTOP', 'LAPTOP']], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='disco_duro',
            field=models.CharField(choices=[['100GB', '100GB'], ['120GB', '120GB'], ['200GB', '200GB'], ['250GB', '250GB'], ['500GB', '500GB'], ['1TB', '1TB']], max_length=100),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='estado',
            field=models.CharField(choices=[['Nuevo', 'Nuevo'], ['Usado', 'Usado'], ['Activo', 'Activo'], ['Inactivo', 'Inactivo'], ['Desuso', 'Desuso']], max_length=100),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='marca',
            field=models.CharField(choices=[['Lenovo', 'Lenovo'], ['Dell', 'Dell'], ['HP', 'HP'], ['Lenovo', 'Lenovo'], ['Epson', 'Epson'], ['Samsung', 'Samsung'], ['Alcatel', 'Alcatel'], ['Generico', 'Generico']], max_length=100),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='memoria_ram',
            field=models.CharField(choices=[['2GB', '2GB'], ['4GB', '4GB'], ['6GB', '6GB'], ['8GB', '8GB'], ['16GB', '16GB'], ['32GB', '32GB']], max_length=100),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='sistema_operativo',
            field=models.CharField(choices=[['Windows 7', 'Windows 7'], ['Windows 10', 'Windows 10'], ['Android', 'Android'], ['Otros', 'Otros']], max_length=100),
        ),
        migrations.AlterField(
            model_name='impresoras',
            name='estado',
            field=models.CharField(choices=[['Nuevo', 'Nuevo'], ['Usado', 'Usado'], ['Activo', 'Activo'], ['Inactivo', 'Inactivo'], ['Desuso', 'Desuso']], max_length=100),
        ),
        migrations.AlterField(
            model_name='impresoras',
            name='marca',
            field=models.CharField(choices=[['Lenovo', 'Lenovo'], ['Dell', 'Dell'], ['HP', 'HP'], ['Lenovo', 'Lenovo'], ['Epson', 'Epson'], ['Samsung', 'Samsung'], ['Alcatel', 'Alcatel'], ['Generico', 'Generico']], max_length=100),
        ),
        migrations.AlterField(
            model_name='monitores',
            name='estado',
            field=models.CharField(choices=[['Nuevo', 'Nuevo'], ['Usado', 'Usado'], ['Activo', 'Activo'], ['Inactivo', 'Inactivo'], ['Desuso', 'Desuso']], max_length=100),
        ),
        migrations.AlterField(
            model_name='monitores',
            name='marca',
            field=models.CharField(choices=[['Lenovo', 'Lenovo'], ['Dell', 'Dell'], ['HP', 'HP'], ['Lenovo', 'Lenovo'], ['Epson', 'Epson'], ['Samsung', 'Samsung'], ['Alcatel', 'Alcatel'], ['Generico', 'Generico']], max_length=100),
        ),
        migrations.AlterField(
            model_name='perifericos',
            name='estado',
            field=models.CharField(choices=[['Nuevo', 'Nuevo'], ['Usado', 'Usado'], ['Activo', 'Activo'], ['Inactivo', 'Inactivo'], ['Desuso', 'Desuso']], max_length=100),
        ),
        migrations.AlterField(
            model_name='perifericos',
            name='marca',
            field=models.CharField(choices=[['Lenovo', 'Lenovo'], ['Dell', 'Dell'], ['HP', 'HP'], ['Lenovo', 'Lenovo'], ['Epson', 'Epson'], ['Samsung', 'Samsung'], ['Alcatel', 'Alcatel'], ['Generico', 'Generico']], max_length=100),
        ),
        migrations.AlterField(
            model_name='telefonia',
            name='estado',
            field=models.CharField(choices=[['Nuevo', 'Nuevo'], ['Usado', 'Usado'], ['Activo', 'Activo'], ['Inactivo', 'Inactivo'], ['Desuso', 'Desuso']], max_length=100),
        ),
        migrations.AlterField(
            model_name='telefonia',
            name='marca',
            field=models.CharField(choices=[['Lenovo', 'Lenovo'], ['Dell', 'Dell'], ['HP', 'HP'], ['Lenovo', 'Lenovo'], ['Epson', 'Epson'], ['Samsung', 'Samsung'], ['Alcatel', 'Alcatel'], ['Generico', 'Generico']], max_length=100),
        ),
        migrations.AlterField(
            model_name='telefonia',
            name='sistema_operativo',
            field=models.CharField(choices=[['Windows 7', 'Windows 7'], ['Windows 10', 'Windows 10'], ['Android', 'Android'], ['Otros', 'Otros']], max_length=100),
        ),
    ]
