# Generated by Django 4.1.1 on 2022-10-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTIPRO', '0012_equipos_tipo_alter_equipos_disco_duro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serieproducto', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[['GENIUS', 'GENIUS'], ['LENOVO', 'LENOVO']], max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[['Nuevo', 'Nuevo'], ['Usado', 'Usado'], ['Activo', 'Activo'], ['Inactivo', 'Inactivo'], ['Desuso', 'Desuso']], max_length=100)),
                ('observaciones', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serieproducto', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[['GENIUS', 'GENIUS'], ['LENOVO', 'LENOVO'], ['LOGITEC', 'LOGITEC']], max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[['Nuevo', 'Nuevo'], ['Usado', 'Usado'], ['Activo', 'Activo'], ['Inactivo', 'Inactivo'], ['Desuso', 'Desuso']], max_length=100)),
                ('observaciones', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipos',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='impresoras',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='monitores',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='perifericos',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='perifericos',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='telefonia',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='equipos',
            name='marca',
            field=models.CharField(choices=[['Lenovo', 'Lenovo'], ['Dell', 'Dell'], ['HP', 'HP'], ['Generico', 'Generico']], max_length=100),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='procesador',
            field=models.CharField(choices=[['AMD A6-3500', 'AMD A6-3500'], ['AMD A6-6400', 'AMD A6-6400'], ['CELERON G1610', 'CELERON G1610'], ['CELERON G550', 'CELERON G550'], ['I3 7100U', 'I3 7100U'], ['I5 8400', 'I5 8400'], ['I5-1035G1', 'I5-1035G1'], ['I5-3570', 'I5-3570'], ['I5-8265U', 'I5-8265U'], ['RYZEN-5 5500U', 'RYZEN-5 5500U']], max_length=50),
        ),
        migrations.AlterField(
            model_name='impresoras',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monitores',
            name='marca',
            field=models.CharField(choices=[['LG', 'LG'], ['DELL', 'DELL'], ['HP', 'HP'], ['AOC', 'AOC']], max_length=100),
        ),
        migrations.AlterField(
            model_name='perifericos',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perifericos',
            name='tipo_periferico',
            field=models.CharField(choices=[['Audifonos', 'Audifonos'], ['Adaptador inalambrico', 'Adaptador inalambrico'], ['Webcam', 'Webcam'], ['Cargadores', 'Cargadores'], ['Cargadores', 'Cargadores'], ['Otros', 'Otros']], max_length=100),
        ),
        migrations.AlterField(
            model_name='telefonia',
            name='marca',
            field=models.CharField(max_length=100),
        ),
    ]
