# Generated by Django 4.1.1 on 2022-10-23 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioTIPRO', '0013_mouse_teclado_remove_equipos_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='impresoras',
        ),
        migrations.AddField(
            model_name='persona',
            name='mouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.mouse'),
        ),
        migrations.AddField(
            model_name='persona',
            name='teclado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventarioTIPRO.teclado'),
        ),
    ]
